# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Version number for caching (needs updating after dependency install/update/change etc.)
parameters:
  package-version:
    type: string
    default: "v1.0.0"

jobs:
  checkout_code:
    docker:
      - image: circleci/node:lts
    working_directory: ~/enmust/enarmustonen
    steps:
      - checkout
      - save_cache:
          key: << pipeline.parameters.package-version >>-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/enmust/enarmustonen

  install:
    docker:
      - image: circleci/node:lts
    working_directory: ~/genmust/enarmustonen
    steps:
      - restore_cache:
          key: << pipeline.parameters.package-version >>-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: << pipeline.parameters.package-version >>-bundle-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Npm disabling progress bar and adding depth 0
          command: npm set progress=false && npm config set depth 0
      - run:
          name: Installing packages
          command: npm install
      - save_cache:
          key: << pipeline.parameters.package-version >>-bundle-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ./node_modules
            - ./package-lock.json

  deploy:
    docker:
      - image: circleci/node:lts
    working_directory: ~/enmust/enarmustonen
    steps:
      - restore_cache:
          key: << pipeline.parameters.package-version >>-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: << pipeline.parameters.package-version >>-bundle-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Run deploy.sh
          command: sh deploy.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
      - install:
          requires:
            - checkout_code
      - deploy:
          requires:
            - install
          filters:
            branches:
              only: master
